# Generated by Django 5.2.1 on 2025-07-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentoexame',
            name='exame',
        ),
        migrations.AddField(
            model_name='agendamentoexame',
            name='exame_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exameprocedimento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='agendamentoexame',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='agendamentoexame',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='exameprocedimento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exameprocedimento',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialidade'),
        ),
        migrations.AlterField(
            model_name='exameprocedimento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medico',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidadesaude'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status_leitura',
            field=models.CharField(choices=[('Lido', 'Lido'), ('Nao Lido', 'Não Lido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ocorrenciapaciente',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='ocorrenciapaciente',
            name='tipo',
            field=models.CharField(choices=[('Atraso', 'Atraso'), ('Faltou', 'Faltou'), ('Reclamou', 'Reclamou')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_risco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.gruporisco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='prioridade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='endereco',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
